### ISSUE TITLE
hex(000) != dec(1) 

### ISSUE THREAD

**Issue by RandyMcMillan** [Coldcard/wordlist-paper#3]
![Screen Shot 2022-04-11 at 11 35 43 AM](https://user-images.githubusercontent.com/152159/162777442-2b02c835-72fc-4e72-acec-e262a6af0ace.png)

**Comment by RandyMcMillan** [comment]
I would think that the word index of the decimal list would map to the corresponding hex value.

**Comment by doc-hex** [comment]
Highly subjective/debatable, but the logic is:

hex(0) => first => dec(1)

... or you can view it as compatibility with other systems/expectations.

**Comment by RandyMcMillan** [comment]
Wow - I guess I assumed the mapping was value for value since `abandon` would be at index 0 in an array/dict/whatever.

**Comment by doc-hex** [comment]
Certainly as a programer, I agree all lists/arrays start at zero. That's why I'm `#0 Dad`
